{application,web_soc,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{web_soc_app,[]}},
              {applications,[kernel,stdlib,cowboy]},
              {env,[]},
              {modules,[web_soc_app,web_soc_sup,ws_handler]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
